# turn a character vector into a named list of words with the
# original being the name/key and the value being the lowered / non-punctuation version
vec2words <- function(vec, reduce = TRUE){

    # remove dupe elements of vector b/c alters frequency of larger document
    # and shows that it was only typed actively once, therefore not a conscious
    # decision to spell correctly after N = 1.
    if(reduce){ vec <- unique(vec) }

    vec <- vec[ !is.na(vec) ] # remove NA elements of vector
    vec <- tolower(vec) # lowercase everything
    vec <- gsub("[[:punct:]]", " ", vec) # rm punctuation incl. hyphens
    vec <- gsub("\\d+", " ", vec) # rm digits
    vec <- gsub("\\s{2,}", " ", vec) # rm extra spaces generated by previous lines
    words <- unlist(strsplit(vec, " ")) # make list of words
    words <- words[ nchar(words) > 2 ] # remove words with only 1 character, possibly due to subs

    return(words)
}

# wrapper for vec2words for dataframe
df2words <- function(df, reduce = TRUE){
    words <- unlist(apply(df, 2, vec2words, reduce))
    return(words)
}

# wrapper for vec2words for list of vectors
list2words <- function(ls, reduce = TRUE){
    words <- unlist(lapply(ls, vec2words, reduce))
    return(words)
}

